config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-compose:
      branch: main
      repo: https://github.com/ai4os/ai4-compose
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-russet-crocodile.sh
        container: qc.acc_slimy-flax-saola
  QC.Doc:
    repos:
      github.com/ai4os/ai4-compose find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-asparagus-moose.sh
        container: qc.doc_craggy-ochre-frog
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-sepia-toucan.sh
        container: qc.doc_sunny-gold-harrier
  QC.Lic:
    repos:
      github.com/ai4os/ai4-compose licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-khaki-oriole.sh
        container: qc.lic_scummy-orchid-rhinoceros
  QC.Ver:
    repos:
      github.com/ai4os/ai4-compose get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-puce-woodlouse.sh
        container: qc.ver_trippy-puce-nightingale
timeout: 5400
