config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-compose:
      branch: main
      repo: https://github.com/ai4os/ai4-compose
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cyan-fly.sh
        container: qc.acc_leaky-black-forest
  QC.Doc:
    repos:
      github.com/ai4os/ai4-compose find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-ivory-capuchin.sh
        container: qc.doc_trippy-corn-uakari
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-pink-lemming.sh
        container: qc.doc_muggy-ochre-jaguar
      github.com/ai4os/ai4-compose markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-rust-bulldog.sh
        container: qc.doc_snippy-sepia-corgi
  QC.Lic:
    repos:
      github.com/ai4os/ai4-compose licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-gold-warthog.sh
        container: qc.lic_snoopy-gamboge-mule
  QC.Met:
    repos:
      github.com/ai4os/ai4-compose cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-saffron-lobster.sh
        container: qc.met_muggy-bronze-gharial
      github.com/ai4os/ai4-compose validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-lemon-grasshopper.sh
        container: qc.met_chummy-gamboge-budgerigar
  QC.Sec:
    repos:
      github.com/ai4os/ai4-compose bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-brass-mandrill.sh
        container: qc.sec_droopy-grey-coati
  QC.Sty:
    repos:
      github.com/ai4os/ai4-compose flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-brass-bee.sh
        container: qc.sty_woolly-linen-rattlesnake
      github.com/ai4os/ai4-compose hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-sepia-centipede.sh
        container: qc.sty_wiggy-silver-chameleon
      github.com/ai4os/ai4-compose jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-ochre-gibbon.sh
        container: qc.sty_flimsy-linen-whale
  QC.Uni:
    repos:
      github.com/ai4os/ai4-compose pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-celadon-bat.sh
        container: qc.uni_wiggy-cobalt-devil
  QC.Ver:
    repos:
      github.com/ai4os/ai4-compose get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-grey-woodpecker.sh
        container: qc.ver_flimsy-pink-mammoth
timeout: 5400
