config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-compose:
      branch: main
      repo: https://github.com/ai4os/ai4-compose
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cinnamon-walrus.sh
        container: qc.acc_stinky-black-shrimp
  QC.Doc:
    repos:
      github.com/ai4os/ai4-compose find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-gold-rat.sh
        container: qc.doc_flimsy-sapphire-tzu
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-sapphire-woodpecker.sh
        container: qc.doc_snoopy-malachite-flounder
  QC.Lic:
    repos:
      github.com/ai4os/ai4-compose licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-ruby-collie.sh
        container: qc.lic_jumpy-lilac-fox
  QC.Ver:
    repos:
      github.com/ai4os/ai4-compose get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-pear-dunker.sh
        container: qc.ver_gamy-wheat-gharial
timeout: 5400
