config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-compose:
      branch: main
      repo: https://github.com/ai4os/ai4-compose
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-razzmatazz-sloth.sh
        container: qc.acc_bumpy-maroon-ant
  QC.Doc:
    repos:
      github.com/ai4os/ai4-compose find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-cerise-bongo.sh
        container: qc.doc_grumpy-alizarin-bracke
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-turquoise-ibis.sh
        container: qc.doc_leaky-platinum-mole
  QC.Lic:
    repos:
      github.com/ai4os/ai4-compose licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-amber-bracke.sh
        container: qc.lic_bluesy-rose-wallaby
  QC.Ver:
    repos:
      github.com/ai4os/ai4-compose get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-carmine-gerbil.sh
        container: qc.ver_ready-bistre-hummingbird
timeout: 5400
