config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-compose:
      branch: main
      repo: https://github.com/ai4os/ai4-compose
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-peach-dane.sh
        container: qc.acc_shabby-cobalt-dingo
  QC.Doc:
    repos:
      github.com/ai4os/ai4-compose find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-olive-meerkat.sh
        container: qc.doc_stinky-brass-coral
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-khaki-lionfish.sh
        container: qc.doc_chewy-viridian-lion
  QC.Lic:
    repos:
      github.com/ai4os/ai4-compose licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-aqua-dunker.sh
        container: qc.lic_bumpy-emerald-hedgehog
  QC.Ver:
    repos:
      github.com/ai4os/ai4-compose get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-denim-stoat.sh
        container: qc.ver_gummy-burgundy-toucan
timeout: 5400
