config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-compose:
      branch: main
      repo: https://github.com/ai4os/ai4-compose
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-myrtle-woodlouse.sh
        container: qc.acc_nerdy-gold-penguin
  QC.Doc:
    repos:
      github.com/ai4os/ai4-compose find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-bistre-molly.sh
        container: qc.doc_clammy-lilac-lizard
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-rust-kingfisher.sh
        container: qc.doc_hazy-magenta-worm
  QC.Lic:
    repos:
      github.com/ai4os/ai4-compose licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-plum-husky.sh
        container: qc.lic_lanky-rose-dugong
  QC.Ver:
    repos:
      github.com/ai4os/ai4-compose get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-seashell-collie.sh
        container: qc.ver_blurry-olivine-macaw
timeout: 5400
