config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-compose:
      branch: main
      repo: https://github.com/ai4os/ai4-compose
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-lime-chinook.sh
        container: qc.acc_beady-magnolia-binturong
  QC.Doc:
    repos:
      github.com/ai4os/ai4-compose find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-azure-argentino.sh
        container: qc.doc_surly-platinum-tang
      github.com/ai4os/ai4-compose git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-cobalt-loon.sh
        container: qc.doc_squirrely-tomato-oyster
      github.com/ai4os/ai4-compose markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-maroon-oyster.sh
        container: qc.doc_lovely-cinnabar-rhinoceros
  QC.Lic:
    repos:
      github.com/ai4os/ai4-compose licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-maroon-birman.sh
        container: qc.lic_hilly-magnolia-lizard
  QC.Met:
    repos:
      github.com/ai4os/ai4-compose cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-copper-numbat.sh
        container: qc.met_lanky-lime-duck
      github.com/ai4os/ai4-compose validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-thistle-buffalo.sh
        container: qc.met_boozy-mustard-drever
  QC.Sec:
    repos:
      github.com/ai4os/ai4-compose bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-ultramarine-anteater.sh
        container: qc.sec_freaky-sangria-russel
  QC.Sty:
    repos:
      github.com/ai4os/ai4-compose flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-thistle-flounder.sh
        container: qc.sty_squeaky-yellow-terrier
      github.com/ai4os/ai4-compose hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-scarlet-seal.sh
        container: qc.sty_lovely-taupe-tetra
      github.com/ai4os/ai4-compose jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-black-meerkat.sh
        container: qc.sty_hasty-vermilion-squirrel
  QC.Uni:
    repos:
      github.com/ai4os/ai4-compose pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-chartreuse-duck.sh
        container: qc.uni_baggy-sapphire-barb
  QC.Ver:
    repos:
      github.com/ai4os/ai4-compose get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-cream-coati.sh
        container: qc.ver_lanky-bronze-hyrax
timeout: 5400
